/* Textes du jeu de reines en espagnol et en portugais du Brésil (9 oct. 2026). Chargé avant game.js.
   La clé est le texte français du code. Un texte absent retombe sur l'anglais. Vérification : `node jeux/tools/langues.js reines`.
   Espagnol : neutre, tutoiement. Portugais : du Brésil, « você ». Vocabulaire : reine = reina / rainha ; zone = zona ; croix = X. */
(function (C) {
  C.i18n({
    'Une reine par ligne, par colonne et par zone de couleur.': 'Una reina en cada fila, columna y zona de color.',
    'Deux reines ne se touchent jamais, même en coin.': 'Dos reinas nunca se tocan, ni en diagonal.',
    'ANNULER': 'DESHACER', 'CROIX AUTO': 'X AUTO', 'OUI': 'SÍ', 'NON': 'NO', 'DIFFICILE': 'DIFÍCIL', 'RÉSOLU !': '¡RESUELTO!',
    'Il ne reste qu’une case libre dans cette ligne : c’est une reine.': 'Solo queda una casilla libre en esta fila: es una reina.',
    'Il ne reste qu’une case libre dans cette colonne : c’est une reine.': 'Solo queda una casilla libre en esta columna: es una reina.',
    'Il ne reste qu’une case libre dans cette zone : c’est une reine.': 'Solo queda una casilla libre en esta zona: es una reina.',
    'Cette zone tient dans une seule ligne : sa reine y sera. Le reste de la ligne est exclu.': 'Esta zona cabe en una sola fila: su reina estará ahí. El resto de la fila queda descartado.',
    'Cette zone tient dans une seule colonne : sa reine y sera. Le reste de la colonne est exclu.': 'Esta zona cabe en una sola columna: su reina estará ahí. El resto de la columna queda descartado.',
    'Ces {m} zones tiennent dans {m} lignes : elles en prennent toutes les reines. Le reste de ces lignes est exclu.': 'Estas {m} zonas caben en {m} filas: se quedan con todas sus reinas. El resto de esas filas queda descartado.',
    'Ces {m} zones tiennent dans {m} colonnes : elles en prennent toutes les reines. Le reste de ces colonnes est exclu.': 'Estas {m} zonas caben en {m} columnas: se quedan con todas sus reinas. El resto de esas columnas queda descartado.',
    'Les cases libres de cette ligne sont toutes dans la même zone : le reste de la zone est exclu.': 'Las casillas libres de esta fila están todas en la misma zona: el resto de la zona queda descartado.',
    'Les cases libres de cette colonne sont toutes dans la même zone : le reste de la zone est exclu.': 'Las casillas libres de esta columna están todas en la misma zona: el resto de la zona queda descartado.',
    'Les cases libres de ces {m} lignes sont dans {m} zones seulement : le reste de ces zones est exclu.': 'Las casillas libres de estas {m} filas están en solo {m} zonas: el resto de esas zonas queda descartado.',
    'Les cases libres de ces {m} colonnes sont dans {m} zones seulement : le reste de ces zones est exclu.': 'Las casillas libres de estas {m} columnas están en solo {m} zonas: el resto de esas zonas queda descartado.',
    'Une reine ici ne laisserait aucune case libre dans cette ligne : case exclue.': 'Una reina aquí no dejaría ninguna casilla libre en esta fila: casilla descartada.',
    'Une reine ici ne laisserait aucune case libre dans cette colonne : case exclue.': 'Una reina aquí no dejaría ninguna casilla libre en esta columna: casilla descartada.',
    'Une reine ici ne laisserait aucune case libre dans cette zone : case exclue.': 'Una reina aquí no dejaría ninguna casilla libre en esta zona: casilla descartada.',
    'Une reine ici mène à une impasse quelques coups plus loin : case exclue.': 'Una reina aquí lleva a un callejón sin salida unas jugadas después: casilla descartada.',
    'Voici une reine.': 'Aquí va una reina.', 'Ces cases étaient fausses : elles sont effacées.': 'Estas casillas estaban mal: se han borrado.',
    'COMMENT JOUER': 'CÓMO JUGAR', 'PASSER': 'SALTAR', 'À TOI DE JOUER !': '¡TE TOCA!', 'Touche-la deux fois.': 'Tócala dos veces.', 'Cette zone n’a qu’une case : sa reine est ici.': 'Esta zona solo tiene una casilla: su reina va aquí.', 'Encore une fois !': '¡Otra vez!',
    'Une reine barre sa ligne, sa colonne, sa zone et les cases qui la touchent. Touche l’écran pour continuer.': 'Una reina tacha su fila, su columna, su zona y las casillas que la tocan. Toca la pantalla para continuar.',
    'Astuce : touche une fois pour barrer une case, glisse pour en barrer plusieurs.': 'Consejo: toca una vez para tachar una casilla, desliza para tachar varias.',
    'RUCHER {n}': 'COLMENAR {n}', 'Il y a {n} erreur sur le plateau.': 'Hay {n} error en el tablero.', 'Il y a {n} erreurs sur le plateau.': 'Hay {n} errores en el tablero.', 'Tout est juste jusqu’ici.': 'Todo está bien hasta aquí.',
    'Vérifier': 'Comprobar', 'Dit si tes reines et tes croix sont justes, sans montrer la suite.': 'Te dice si tus reinas y tus X están bien, sin mostrar lo que sigue.',
    'PREMIERS PAS': 'PRIMEROS PASOS', 'GRILLES {n} × {n}': 'TABLEROS {n} × {n}',
    'Musique : Kevin MacLeod (incompetech.com), licence CC BY 4.0 · Bruitages : Kenney (kenney.nl)': 'Música: Kevin MacLeod (incompetech.com), licencia CC BY 4.0 · Sonidos: Kenney (kenney.nl)',
    'Indice': 'Pista', 'Joue le prochain coup et explique le raisonnement.': 'Hace la siguiente jugada y explica el razonamiento.',
  }, 'es');
  C.i18n({
    'Une reine par ligne, par colonne et par zone de couleur.': 'Uma rainha em cada linha, coluna e zona de cor.',
    'Deux reines ne se touchent jamais, même en coin.': 'Duas rainhas nunca se tocam, nem na diagonal.',
    'ANNULER': 'DESFAZER', 'CROIX AUTO': 'X AUTO', 'OUI': 'SIM', 'NON': 'NÃO', 'DIFFICILE': 'DIFÍCIL', 'RÉSOLU !': 'RESOLVIDO!',
    'Il ne reste qu’une case libre dans cette ligne : c’est une reine.': 'Só resta uma casa livre nesta linha: é uma rainha.',
    'Il ne reste qu’une case libre dans cette colonne : c’est une reine.': 'Só resta uma casa livre nesta coluna: é uma rainha.',
    'Il ne reste qu’une case libre dans cette zone : c’est une reine.': 'Só resta uma casa livre nesta zona: é uma rainha.',
    'Cette zone tient dans une seule ligne : sa reine y sera. Le reste de la ligne est exclu.': 'Esta zona cabe em uma única linha: a rainha dela estará ali. O resto da linha está descartado.',
    'Cette zone tient dans une seule colonne : sa reine y sera. Le reste de la colonne est exclu.': 'Esta zona cabe em uma única coluna: a rainha dela estará ali. O resto da coluna está descartado.',
    'Ces {m} zones tiennent dans {m} lignes : elles en prennent toutes les reines. Le reste de ces lignes est exclu.': 'Estas {m} zonas cabem em {m} linhas: elas ficam com todas as rainhas. O resto dessas linhas está descartado.',
    'Ces {m} zones tiennent dans {m} colonnes : elles en prennent toutes les reines. Le reste de ces colonnes est exclu.': 'Estas {m} zonas cabem em {m} colunas: elas ficam com todas as rainhas. O resto dessas colunas está descartado.',
    'Les cases libres de cette ligne sont toutes dans la même zone : le reste de la zone est exclu.': 'As casas livres desta linha estão todas na mesma zona: o resto da zona está descartado.',
    'Les cases libres de cette colonne sont toutes dans la même zone : le reste de la zone est exclu.': 'As casas livres desta coluna estão todas na mesma zona: o resto da zona está descartado.',
    'Les cases libres de ces {m} lignes sont dans {m} zones seulement : le reste de ces zones est exclu.': 'As casas livres destas {m} linhas estão em apenas {m} zonas: o resto dessas zonas está descartado.',
    'Les cases libres de ces {m} colonnes sont dans {m} zones seulement : le reste de ces zones est exclu.': 'As casas livres destas {m} colunas estão em apenas {m} zonas: o resto dessas zonas está descartado.',
    'Une reine ici ne laisserait aucune case libre dans cette ligne : case exclue.': 'Uma rainha aqui não deixaria nenhuma casa livre nesta linha: casa descartada.',
    'Une reine ici ne laisserait aucune case libre dans cette colonne : case exclue.': 'Uma rainha aqui não deixaria nenhuma casa livre nesta coluna: casa descartada.',
    'Une reine ici ne laisserait aucune case libre dans cette zone : case exclue.': 'Uma rainha aqui não deixaria nenhuma casa livre nesta zona: casa descartada.',
    'Une reine ici mène à une impasse quelques coups plus loin : case exclue.': 'Uma rainha aqui leva a um beco sem saída algumas jogadas depois: casa descartada.',
    'Voici une reine.': 'Aqui vai uma rainha.', 'Ces cases étaient fausses : elles sont effacées.': 'Estas casas estavam erradas: foram apagadas.',
    'COMMENT JOUER': 'COMO JOGAR', 'PASSER': 'PULAR', 'À TOI DE JOUER !': 'SUA VEZ!', 'Touche-la deux fois.': 'Toque nela duas vezes.', 'Cette zone n’a qu’une case : sa reine est ici.': 'Esta zona só tem uma casa: a rainha dela fica aqui.', 'Encore une fois !': 'Mais uma vez!',
    'Une reine barre sa ligne, sa colonne, sa zone et les cases qui la touchent. Touche l’écran pour continuer.': 'Uma rainha risca a linha, a coluna, a zona dela e as casas que encostam nela. Toque na tela para continuar.',
    'Astuce : touche une fois pour barrer une case, glisse pour en barrer plusieurs.': 'Dica: toque uma vez para riscar uma casa, deslize para riscar várias.',
    'RUCHER {n}': 'APIÁRIO {n}', 'Il y a {n} erreur sur le plateau.': 'Há {n} erro no tabuleiro.', 'Il y a {n} erreurs sur le plateau.': 'Há {n} erros no tabuleiro.', 'Tout est juste jusqu’ici.': 'Tudo certo até aqui.',
    'Vérifier': 'Verificar', 'Dit si tes reines et tes croix sont justes, sans montrer la suite.': 'Diz se suas rainhas e seus X estão certos, sem mostrar o que vem depois.',
    'PREMIERS PAS': 'PRIMEIROS PASSOS', 'GRILLES {n} × {n}': 'GRADES {n} × {n}',
    'Musique : Kevin MacLeod (incompetech.com), licence CC BY 4.0 · Bruitages : Kenney (kenney.nl)': 'Música: Kevin MacLeod (incompetech.com), licença CC BY 4.0 · Sons: Kenney (kenney.nl)',
    'Indice': 'Dica', 'Joue le prochain coup et explique le raisonnement.': 'Faz a próxima jogada e explica o raciocínio.',
  }, 'pt');
})(window.Core);
